<%@ Page Title="" Language="VB" MasterPageFile="~/News.master" AutoEventWireup="false" CodeFile="verizonnews.aspx.vb" Inherits="verizonnews" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
       <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="page-header">
                            <h3>Where Will Verizon’s Price Go After the Buyout?<small><br />Posted on October 21, 2013</small></h3>
                        </div>
                        <h4>Verizon Communication Inc. (VZ) Intrinsic Price Estimate: $39.81</h4>
                        <p>On September 2nd, 2013, Verizon Communications Inc. (VZ) announced that it has
                            entered into a definitive agreement with Vodafone Group Plc. (VOD). Verizon will
                            acquire Vodafone’s stake in Verizon Wireless for $130 billion. </p>
                        <p>Before the buyout, Vodafone held 45% ownership stake of Verizon Wireless. Verizon
                            had to share 45% of profits that were generated by Verizon Wireless with Vodafone.
                            This presented a challenge to value Verizon since the company did not disclose
                            sufficient financial information about its Wireless subsidiary. However, the purchase
                            of the 45% stake from Vodafone makes it possible to value Verizon Communication
                            as a whole without requiring separate information about its Wireless subsidiary.</p>
                        <p>We performed free cash flow valuation analysis to determine the intrinsic stock
                            price of Verizon (VZ). We initially disregard the 45% stake by Vodafone on Verizon
                            Wireless. Having obtained valuation that includes the Vodafone stake, we subtract
                            the $130 billion purchase price from it to reach an intrinsic value estimate for VZ. </p>
                        <p>Our valuation analysis relies on analysts’ consensus revenue projections, and
                            assuming continued profit margin and investment intensity from past years. For
                            those who are interested in the details of our valuation process, key numbers are
                            summarized in the appendix and a link to a spreadsheet file is provided at the end
                            of the Appendix. </p>
                        <p>In a nutshell, our estimate of VZ’s intrinsic stock price is $39.81. This is almost $11
                            below Verizon’s share price of $50.58 on October 21, 2013. We also use the same
                            approach to value AT&T (T) and end up with an intrinsic price estimate of $32.28,
                            $2.96 lower than the market price as of October 21. Part of the discrepancies
                            between the intrinsic and market prices for both companies reflects investor
                            optimism in the current market environment. However, Verizon’s market price
                            appears to be more overvalued, relative to AT&T. Possibly the market believes that
                            Verizon Wireless, unshackled from Vodafone, may be able to invest moreaggressively in the 4G capacity and capture a bigger market share from its
                            competitors. We have yet to see if this expectation materializes.</p>
                        <!--first table-->
                       <br />
                        <br />
                        <p>About Pentacrest Value Institute (PVI): PVI is a non-profit institute that promotes rigorous fundamental and 
                            quantitative equity research. PVI is not an investment advisor or broker. It does not hold any positions on the 
                            companies mentioned in the article, and this article is not intended to recommend any stocks to the public.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</asp:Content>

